### ISSUE TITLE
550 response on PUT /portal/apptreeSettings

### ISSUE THREAD

**Issue by sambbaron** [apptreesoftware/revolution#103]
I suspect this might be an issue of field size.  I am trying to update a CONFIG default setting with a fairly long JSON chunk.

I am getting this response:
```javascript
{"message":"A database error occurred trying to process this request. Please contact support@apptreesoftware.com"}
```

[curl.txt](https://github.com/apptreesoftware/revolution/files/537607/curl.txt)

**Comment by alexisandreason** [comment]
You were right that it was a column size error. I upped the size of the column and was able to save using the given curl.

**Comment by sambbaron** [comment]
@alexisandreason This is an issue again.  I'm not sure if you increased the column size enough.

Here's the cURL:
[curl.txt](https://github.com/apptreesoftware/revolution/files/540563/curl.txt)

**Comment by alexisandreason** [comment]
I had forgotten to put the column increase in the database migration script. It is fixed now.
