### ISSUE TITLE
5.4.4 Scan Barcode On Create Form and App Crashes

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#104]
Scan barcode on create form and app crashes

Log into the mobile application as user rkromer.
Navigate to Create Service Request
Scan barcode (attached)
App crashes

App ID:  service.taylorfreezer.net

iOS 10.0.2
5.4.4 (2160)
![taylorfreezer_k1036405_qr_code](https://cloud.githubusercontent.com/assets/22403044/19500777/5cb426dc-956e-11e6-80d4-dd2b88f2fdfe.png)

**Comment by mellissatort** [comment]
New SDK is deployed for this connector when testing.

**Comment by matthewtsmith** [comment]
Fixed in 5.4.4r2214

**Comment by matthewtsmith** [comment]
@mellissatort if a bug still occurs please reopen otherwise its hard to find.
