### ISSUE TITLE
Can't test '/portal/connectors/:connectorID/endpoint' from localhost

### ISSUE THREAD

**Issue by sambbaron** [apptreesoftware/revolution#105]
When I call `POST /portal/connectors/:connectorID/endpoint` from localhost, I get a 503 error:

**XMLHttpRequest cannot load https://services1.apptreesoftware.com/portal/connectors/657/endpoint. 
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'http://localhost:63342' is therefore not allowed access. 
The response had HTTP status code 503.**

In this case, it was the `inspect.corrigo.com` app.  Here's the full cURL:
[curl.txt](https://github.com/apptreesoftware/revolution/files/539671/curl.txt)

This is a problem when I am running the Portal locally and need to test.

_Not sure if this is a Core or SDK issue, but I am assigning to Core since that's where the call originates in the Portal_

**Comment by sambbaron** [comment]
@matthewtsmith FYI

**Comment by alexisandreason** [comment]
@sambbaron The connector URLs were not configured correctly for the inspect.corrigo.com app. I have updated the URLs in sandbox and production and the endpoint call is working now.
