### ISSUE TITLE
Copy App to multiple app IDs and the data connector url overwrite is not updated on some

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#106]
Copy app configuration on one app ID and select multiple app IDs to copy it to.  Edit the connector urls on target app IDs to be correct for the environment.  Upon selecting copy function some of the app IDs selected do not get updated with the correct connector URL.  The user connector settings url does get updated successfully from the copy.

**Steps to Reproduce**
Select app ID somdev.stanford.edu
Select the Copy App button
Do not check any checkboxes
Select Live version to copy
From drop down list select target app ID somint.stanford.edu
Add second target app ID selecting sominta.stanford.edu from the drop down list
Check the option "Copy to Live Version"
Select the Edit Connectors button and overwrite the urls with the following:
User Connector = https://ofeam-mobile-int-pub.stanford.edu/hhsompub/user
SOM Connector = https://ofeam-mobile-int-pub.stanford.edu/hhsompub
Select the Copy button and type OVERWRITE to complete the copy process
Navigate to each of the target app IDs and review the urls.

One of the target app IDs will have the urls updated successfully.  The second target app ID will have the DEV SOM connector url and the INT user connector url.  The SOM connector url entered on the copy app screen was ignored and the DEV url was used instead.

somdev.stanford.edu
Copy to somint.stanford.edu and sominta.stanford.edu

5.4 using Chrome browser

**Comment by sambbaron** [comment]
@mellissatort I think I need the secret keys to the connector overwrites to replicate this.  Alternately, if you want to try this again, you can send me the cURL, and I'll see what's being sent to the Core.

**To get a cURL for a http request (in Chrome)**:
1. Make sure that developer tools is open when you initiate the request: *when you click the __COPY__ button*
2. Go to the `Network` tab of developer tools, and look for the relevant request: */copyApps*
3. Right-click on the request and select `Copy as cURL`
4. You can then paste this into a separate file or directly into this issue comment.

**Comment by mellissatort** [comment]
@sambbaron this is confirmed working.  closing ticket
