### ISSUE TITLE
Allow max length to be set for text attributes in portal configuration

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#107]
Currently text attributes have no length max which can be configured in the portal.  Add max length configuration for text attributes so when users are editing an attribute for update (ie. comments) the text entered will not exceed the max length specified.  If no max length is specified in the configuration then no restrictions will exist on the text attribute.

App ID for testing:  feandpdev.rice.edu
New Time Entry - Comments attribute

5.4 Portal - Chrome browser

**Comment by sambbaron** [comment]
@matthewtsmith I'm assigning this to you for further discussion.  What do you think about implementing this in validation criteria?  We could have criteria operators for min/max length.

**Comment by sambbaron** [comment]
@matthewtsmith @mellissatort I created an issue label for `Configuration` that I think better fits these types of issues.  I think once we get the configuration changes decided, then we can create platform-specific issues.

**Comment by matthewtsmith** [comment]
@mellissatort @sambbaron I don't want to do this as criteria because this is a simple attribute I can set on text fields. Also, criteria is expensive to calculate.

@mellissatort We already have an attribute for this in the client `maxLength`. @sambbaron there are quite a few of these types of settings that the client obeys that we do not have UI for in the portal. When possible, I will start documenting these on our documentation site and we can create tickets to support them.

**Comment by mellissatort** [comment]
@matthewtsmith @sambbaron Since an attribute for maxLength already exists in the client, what would the effort be to build the UI for this in the portal?  Rice University notified me of an issue with the timecard comments field where a user entered a text string longer than what is permitted in FAMIS.  We can modify the database package to prevent this, however if there is a configuration which can enforce it as well prior to submit that would be ideal if the UI can be implemented easily.

**Comment by sambbaron** [comment]
@mellissatort I can do this today.

**Comment by sambbaron** [comment]
@mellissatort You can always add `maxLength` directly to the display element's JSON settings.  I realized that this change is going to have to be wrapped up with some other changes that may not be deployed until later this week.

**Comment by sambbaron** [comment]
@mellissatort This is deployed to sandbox `0.8.0-dev.14`.

**Comment by mellissatort** [comment]
@matthewtsmith I've made the config change in sandbox for feandpdev.rice.edu.  However client 5.4.4 (1086) does not let me select sandbox on the app ID form.  How can I test this on the client for sandbox?

**Comment by matthewtsmith** [comment]
@mellissatort You would need a build that allows the environment selection. The one in Crashlytics might have that enabled.

@sambbaron is there a reason we can't just add this to `portal`. Seems like a low risk change.

**Comment by sambbaron** [comment]
@matthewtsmith @mellissatort Right now, all my view changes are dependent on deploying the integrated help feature.  I was waiting for Alexis to deploy the Core with integrated help, but I might be able to deploy without that.  I need to review.
