### ISSUE TITLE
Sandbox: Can not delete menu item

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/revolution#11]
APP ID: inspections.corrigo.com
SANDBOX

I would like to delete the `Asset Inspection` Menu item.
I click on menu item
Press remove
A blank modal is shown, exception gets logged to console.

**Comment by matthewtsmith** [comment]
@sambbaron I'm still having issues. This time I was prompted with the feature deletion page. After deleting the feature I was taken back to the menu. I expected the menu item to be gone but it was still there with a red disclosure button.  I then tapped on the menu item to try and delete the menu ite again and it just hung.
![screen shot 2016-09-30 at 11 16 16 am](https://cloud.githubusercontent.com/assets/9000800/19002146/82a706a2-86ff-11e6-8f26-c5f47abe161d.png)

**Comment by sambbaron** [comment]
@matthewtsmith I deleted the orphaned menu item from the app, but I am still working on another related bug.

**Comment by sambbaron** [comment]
@matthewtsmith Deploying to sandbox now.  Make sure you are using build version **0.6.0-rc.1**, which you can find in the new about modal.
