### ISSUE TITLE
Authentication configuration should send client the `User Registration URL`

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/revolution#111]
We want to avoid having the clients hard code the user registration URL. We should add `userRegistrationURL` and `userProfileURL` to the AuthenticationInfo.

We should have the ability to set this globally and it can be overridden by a particular app if necessary. 

**These properties should also be available as placeholder tags for user communication templates**

**Comment by matthewtsmith** [comment]
@alexisandreason Assign to @sambbaron to create portal UI when you have the core support for this.

**Comment by alexisandreason** [comment]
@sambbaron userRegistrationURL and userProfileURL have been added to the authParameters object. I also added 2 more apptree global settings for those URLs with the PLATFORM type. So they are returned with the login and getUserForToken calls.
