### ISSUE TITLE
Application info based criteria

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/revolution#114]
We need the ability to enable/disable features based on the version information.

Initially, I'd like to support.

`version` ie. 5.4.3
`buldnumber` ie. 2422
`appid` ie. test.wawa.com

we need to support this on different platforms so the key paths will be the following:

`runtimeContext.app.<platform>.version`

where platform can be
1. base
2. ios
3. android
4. web

**Comment by matthewtsmith** [comment]
@sambbaron assign to me when complete and I will do client work.

**Comment by sambbaron** [comment]
@matthewtsmith  This is deployed to sandbox `0.8.0-dev.22`

**Comment by matthewtsmith** [comment]
@sambbaron We need to update the value types:

BuilderNumber = Int
VersionNumber = Double

**Comment by sambbaron** [comment]
@matthewtsmith This change is deployed to sandbox `0.8.0-dev.24`

**Comment by matthewtsmith** [comment]
Unable to test in the scenario I need because of https://github.com/apptreesoftware/revolution/issues/121

**Comment by sambbaron** [comment]
@matthewtsmith #121 fix has been deployed to sandbox `0.8.0-dev.25`
