### ISSUE TITLE
MenuItems do not have visibleCriteria

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/revolution#121]
When I tap to edit a menu item and add criteria, `visible` is not one of the options:

http://sandbox.apptreesoftware.com/#/app/inspect.corrigo.com/beta/builder

Also, `enable` and `require` are not used on MenuItems so really the only one we want is `visible`.

**Comment by sambbaron** [comment]
@matthewtsmith This has been deployed to sandbox `0.8.0-dev.25`
