### ISSUE TITLE
5.4.4 Map Layout 4 Attributes Color Stripe List Display Layout Is Different

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#123]
Navigate to Part Lookup
Select Part Number list of values
In 5.4.3 version the data was displayed:  top left = Part#, top right = Status, bottom left = Description, bottom right = Warehouse.  Which is actually different than what the list display configuration has.
In 5.4.4 version the data is displayed according to the list display configuration:  top left = Part#, top right = Description, bottom left = Status, bottom right = Warehouse.
However because of this display change any list using this configuration with description in top right will need to be updated.

feandpdev.rice.edu

iOS 5.4.4 (2217)
Android 5.4.5 (1102)

**Comment by matthewtsmith** [comment]
@mellissatort This is actually a bug in 5.4.3 that is fixed in 5.4.4. We have no way to back-support this to 5.4.3. I would recommend making a config update to the template after we release the app and let our customers know they should update.
