### ISSUE TITLE
Add ability to define headers when registering connector

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/revolution#129]
For both Corrigo and Accruent we want to be able to host a single connector that talks to different environments. In order to support this we need to be able to register a connector and headers that should be included in every request.

You should be able to define headers for the User Connector, Authentication Connector and Data connectors.

In the core the headers should be stored in the connector table.

In the portal I envision this being a simple table where I can define the key and the value, both static.

**Comment by matthewtsmith** [comment]
@alexisandreason Assigning to you first for the core work. Assign to @sambbaron when complete.

**Comment by matthewtsmith** [comment]
@alexisandreason marking as critical because I need it to deploy corrigo.

**Comment by alexisandreason** [comment]
@sambbaron There is now a headers JSON field for connectors. It can be updated from the connector update call for regular connectors or with the update auth call for user/auth connectors.

**Comment by sambbaron** [comment]
@matthewtsmith @alexisandreason This is deployed to portal staging `0.7.10-stage.1`
