### ISSUE TITLE
List auto fill not working on registration form

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/revolution#130]
When I go to the registration form for taylor freezer:
http://go.apptreesoftware.com/#/user/register?core=https://services-sandbox.herokuapp.com&app=service.taylorfreezer.net&redirect=http://google.com/&beta=true

After selecting a store, the customer should be auto populated. The configuration for this looks correct in`sandbox.apptreesoftware.com`

<img width="1494" alt="screen shot 2016-10-26 at 9 56 35 am" src="https://cloud.githubusercontent.com/assets/9000800/19735961/891ce03e-9b62-11e6-8b2e-9b39647bb38e.png">

**Comment by johnpryan** [comment]
I'm fairly positive that this is because the Store No has a DataType of TEXT and not LISTITEM

**Comment by johnpryan** [comment]
[Here's the line of code in question](https://github.com/apptreesoftware/apptreerevolution-web/blob/master/lib/page/views/form_view.dart#L521).  I'm not sure how a form element can have a DataType of TEXT but a fieldTypeString as SELECTLIST

**Comment by johnpryan** [comment]
@matthewtsmith Can you clarify?  From what I gather the DataType is how it's displayed but we really should be checking the fieldType on that line.

**Comment by johnpryan** [comment]
This particular form element is set to use attribute 1 of the selected list item.  Is that correct?  From what I can tell that list doesn't have data in attribute 1

**Comment by matthewtsmith** [comment]
Turned out to be a connector issue.
