### ISSUE TITLE
Should be able to add custom attributes to user table display

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/revolution#132]
Sandbox - When on a user list for a given app, I should be able to tap the `Display` button to change which attributes are visible in the table and add a custom attribute:

http://sandbox.apptreesoftware.com/#/app/feandpdev.rice.edu/app-users

Currently only the standard attributes show up.

**Comment by sambbaron** [comment]
@matthewtsmith Fix deployed to sandbox `0.8.0-dev.29`
