### ISSUE TITLE
Portal:  Add LK Zone 2 Menu Item and Save Orphans the new menu item and pages

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#133]
portal.apptreesoftware.com
App ID:  dev.usc.edu  (BETA)

Add new menu item:  Display and Update Multiple Records
Menu Item Name:  LK Zone 2 Work Orders
Select existing feature "My Work Orders (ID: 1390)"
Select data set "LK Zone 2 (ID: 1068)"
Select existing feature "Work Order Details (ID: 1391)"
Press Finish button
The new menu item is at the bottom of the menu list
Press Save button
The new menu item is now no longer on the menu list and when navigate to Page Manager see it is ORPHAN PAGE

**Comment by sambbaron** [comment]
@mellissatort This fix has been deployed to portal build `0.7.9`.  I also created the new feature.  There was a bug that was exposed due to the Core running slow.

**Comment by mellissatort** [comment]
@sambbaron When I try to launch the app ID dev.usc.edu it is acting like it's refreshing for a really long time and not returning me to the device view so I can perform more edits.  I have attached a screenshot of what is appearing in the console.
<img width="1406" alt="screen shot 2016-10-27 at 8 23 25 am" src="https://cloud.githubusercontent.com/assets/22403044/19767002/bc5b3ab0-9c1e-11e6-9e3c-6d796891c18a.png">

**Comment by sambbaron** [comment]
@mellissatort I was able to load the builder.  I clicked around and didn't have any problems.  I do know the Core has been sluggish lately, and I know Matt is working on that. 

![screen shot 2016-10-27 at 3 46 04 pm](https://cloud.githubusercontent.com/assets/10456742/19788329/838bfeb6-9c5c-11e6-8ab9-abddf78dee9f.png)
