### ISSUE TITLE
Web Client not loading registration page.

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/revolution#135]
I'm trying to integrate the registration page into the mobile clients. When I go to:

http://go.apptreesoftware.com/#/user/registration?core=https%3A//services-sandbox.herokuapp.com/&beta=true&app=service.taylorfreezer.net&redirect=apptree%3A//registrationComplete

It does not load the servicemaster registration page.

Its doing two different things depending where I do it from.

1.) from my mobile device it just takes me to the "Enter App ID" screen
2.) On my desktop it takes me to the corrigo login. I presume this is because that is the last App ID I used.

**Comment by johnpryan** [comment]
The url is using /user/registration instead of /user/register.  Try this instead:

http://go.apptreesoftware.com/#/user/register?core=https%3A//services-sandbox.herokuapp.com/&beta=true&app=service.taylorfreezer.net&redirect=apptree%3A//registrationComplete
