### ISSUE TITLE
Add support for custom auth headers

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/revolution#137]
To support Corrigo I've had to add the ability to send custom auth headers during login.

This requires an update to AuthenticationConfiguration and the CoreAuthenticationController. Here is the client commit that adds support for this:

https://github.com/apptreesoftware/apptreerevolution-ios/commit/65e4f10a648a630e84fff2c57118c9d08e12f3b9

**Comment by johnpryan** [comment]
Can you specify the environment and appId that is configured to provide the auth headers?  I am now unable to login to servicemaster.corrigo.com, and the headers are not being provided in the JSON using services1 on sandbox.

**Comment by matthewtsmith** [comment]
@johnpryan I forgot setup the environment in production. I have fixed the settings.

The app ID you should use to test this is `inspect.corrigo.com`
You can find the credentials in 1Password by searching for "Preview Baptist Health"

Use the `coldf` user listed under Other Users.

**Comment by matthewtsmith** [comment]
@johnpryan You should also be able to login to servicemaster.corrigo.com
