### ISSUE TITLE
5.4.4 Sandbox:  New Time Entry not defaulting with Employee value when Choose Employee not selected

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#138]
In 5.4.4 sandbox for both iOS and Android navigate to Timecard menu.
Select + button to add new timecard
Employee field is not defaulted with user's employee value.

If user returns to the timecard calendar screen and selects an employee from Choose Employee select list and then selects the + button to add a new timecard the employee selected is defaulted on the time card.

App ID:  lbreint.stanford.edu
beta and live

iOS 10.0.2   5.4.4 (2227)
Android 6.0.1   5.4.5 (1107)

**Comment by matthewtsmith** [comment]
@mellissatort This turned out to be a core issue. A new core is being deployed to sandbox with the fix.
