### ISSUE TITLE
5.4.5 Android:  New Time Entry work date not defaulting with value based on criteria

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#139]
Navigate to Timecard menu item.
Select + button to add new time entry.
Work date does not default with current date.
Return to the timecard calendar screen and select a different date.
Select + button to add new time entry
Work date does not default with selected date.

lbreint.stanford.edu
services1 or sandbox

Andorid 6.0.1   5.4.5 (1107)
not occurring on iOS

**Comment by matthewtsmith** [comment]
Fixed in 1108.

**Comment by matthewtsmith** [comment]
https://github.com/apptreesoftware/apptreerevolution-android/commit/3234953b00a5d73d50fad3ccf7586e5b32fac98e

**Comment by mellissatort** [comment]
confirmed fixed.  tested 1109
