### ISSUE TITLE
Sandbox Portal:  Navigate to Security Settings and then select Builder and the portal is stuck refreshing

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#140]
Log into Sandbox portal as apptreedev
Select app ID (ie. feandpdev.rice.edu).  Beta and live version exist.
Select Security Settings and scroll to view all details on the page.
Select Builder and the page continues to refresh without a successful end.  Eventually the portal login session times out and returns me to the login screen.

**Comment by sambbaron** [comment]
@mellissatort Fix deployed to portal sandbox `0.8.0-dev.32.1`

**Comment by mellissatort** [comment]
confirmed fixed
