### ISSUE TITLE
5.4.5 Android Sandbox: Time entries not displaying for logged in user

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#142]
Log into the mobile client as kjhchang
Navigate to Timecard
Time entries exist on 10/24 and 10/25 but do not display on 5.4.5 Android client when using sandbox environment.  If switch to services1 they display.  Also displayed on iOS whether using services1 or sandbox.

App ID:  lbreint.stanford.edu
Sandbox

Android 6.0.1   5.4.5 (1108)

**Comment by matthewtsmith** [comment]
Fixed by: https://github.com/apptreesoftware/apptreerevolution-android/commit/f028de7d059b7436cdea7968d89b2dbecaafaf11
