### ISSUE TITLE
Portal/Core: Round activity timer duration up to minutes rather than seconds when sending to the connector

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#143]
When the activity timer duration is displayed on the form it is displayed as minutes, however when the value is passed to the connector it includes seconds.  Can the duration be rounded up to minutes as it is displayed when sending the data to the connector?

From My Work Orders workbench start the timer on a work order and let it run for 1.5 minutes.
Stop the timer with the I'm Done option and it will redirect you to the new time entry form.
The hours are defaulted with the duration at the minute level.
When the time entry is submitted it is submitted with 1.5 minutes instead of 1 minute.

App ID:  feandpdev.rice.edu

**Comment by matthewtsmith** [comment]
@mellissatort I don't think the client should be responsible for this because we can't assume the level of precision that the connector wants. Rounding seems like a function you should perform in the connector based on the business logic you want to support.

**Comment by matthewtsmith** [comment]
@mellissatort I don't plan on fixing this in the client so I'm closing it. If you would like to discuss further you can re-open.

**Comment by mellissatort** [comment]
@matthewtsmith no we do not need to reopen it.  I found a solution for this in the connector we can do instead.
