### ISSUE TITLE
Getting Error When Using FAMIS Branded App

### ISSUE THREAD

**Issue by RobertGuinn** [apptreesoftware/revolution#147]
**Description**

Using FAMIS branded 5.3.12 app from the Apple App Store, I get an error when I try to set an App ID:

"The operation couldn't be completed . (com.alamofire.error error - 6003)

Using the same app id with the equivalent apptree branded build works.

**Steps to Reproduce**

**App ID**

sou.famis.com

**Version Number**

5.3.12

**Comment by matthewtsmith** [comment]
@alexisandreason add the accruent branded app to all famis APP IDs.

**Comment by alexisandreason** [comment]
I did this for Columbia City School, Fresno County, and Southern Oregon University apps. I think that is all of the FAMIS apps, but let me know if I am missing any.
