### ISSUE TITLE
Change Label CAS to Shibboleth

### ISSUE THREAD

**Issue by RobertGuinn** [apptreesoftware/revolution#148]
**Description**

On security settings page, when specifying the central authentication type, change 'CAS' to 'Shibboleth'

**Steps to Reproduce**

**App ID**

**Version Number**

**Comment by sambbaron** [comment]
@matthewtsmith Do you want to change the configuration key/value for this?  

Right now, we have:
```JSON
{
    "authConnector": {
        "connectorID": 123,
        "connectorName": "Authentication Connector",
        "url": "http://www.test.com",
        "type": "AUTH",
        "secretKeySet": false,
        "settings": {
            "casType": "CAS",
            "validateTokenURL": null,
            "serviceURL": null
        }
    }
}
```

We could change to:

```JSON
{
	"settings": {
		*"subType": "shibboleth",*
		"validateTokenURL": null,
		"serviceURL": null
	}
}
```

**Comment by matthewtsmith** [comment]
@sambbaron no, the json can't change because it will break existing apps. Just change the label in the builder UI.

**Comment by sambbaron** [comment]
@matthewtsmith Ok, no problem

**Comment by sambbaron** [comment]
@RobertGuinn Do you want to change any of the authentication descriptions with this change.  We have the `Centralized` description from the dropdown and then the description once the selection is made.

**Dropdown**
> Use this option if you want to integrate your app with an existing Single-Sign-On or centralized authentication service.  Common SSO options are CAS, Shibboleth, Kerberos or custom built central authentication authorities.
> To use this option, you will need to consult with the administrators for the SSO service you want to authenticate to.  You will need to configure the SSO headers and modify your app connectors to handle the auth token that the SSO will provide.  You will also need to build a session verification function into your connector to validate the tokens that are passed in with each mobile app user request.
> 

**Selected**
> This app authenticates using an SSO server or central authentication authority. The user's password is not entered into the app. When your app is launched, the user will be redirected to an SSO login page where they will enter their user credentials. If login is successful, the SSO will return a token to the AppTree app which will be used to validate the session.

**Comment by RobertGuinn** [comment]
@sambbaron  no changes to the descriptions.  There will be changes in the future, but we are waiting until we tackle our next central auth environment to figure this out.
