### ISSUE TITLE
Portal: Cannot add criteria to dev.usc.edu attributes or buttons

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#149]
Unable to add criteria to attributes or buttons within app ID dev.usc.edu.

Navigate to My Work Order.
Select Map button and add criteria for Visible when role is Supervisor.  When select add criteria button the criteria description window displays but unable to select conditions.
Return to My Work Order window.
Navigate to My Work Order Details.
Select Assigned To attribute and add criteria for Require when role is Supervisor.  When select add criteria button the criteria description window displays but unable to select conditions.

I do not have this issue with menu items.

App ID:  dev.usc.edu (beta)
services1

**Comment by mellissatort** [comment]
Additionally unable to add default values to attributes.

**Comment by sambbaron** [comment]
@mellissatort Fix deployed `0.7.11`

Also in the future, can you include the portal url in your github issues for the portal?  It's really helpful for me just to hyperlink to whatever part of the portal the issue relates to.

**Comment by mellissatort** [comment]
@sambbaron has this fix been deployed to portal.apptreesoftware.com so I can test?

**Comment by sambbaron** [comment]
@mellissatort Yes, this is deployed in build `0.7.11`.

**Comment by mellissatort** [comment]
confirmed fixed
