### ISSUE TITLE
Portal:  Add "Enable" option to button criteria list

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#150]
Add "Enable" option to button criteria list.
We have several existing criteria which currently include the "Enable" criteria, however since the new limited list display was installed in portal we no longer have "Enable" in the list to select from for button criteria.

**Comment by mellissatort** [comment]
@sambbaron maybe this is not an issue but rather a question.

On the Resource Detail page exists a Timecard button.
http://portal.apptreesoftware.com/#/app/somdev.stanford.edu/beta/builder/device/page/2142
This Timecard button already has "Enable" criteria configured.
I cannot add a new criteria for Enable because it's already been used so my only option is to add to the existing criteria.
Is the use of a criteria option limited to a one-time use for the item rather than multiple criteria instance uses?

**Comment by sambbaron** [comment]
@mellissatort That's correct.  You can only have one instance of Enable, Require, and Visible criteria.  Criteria types that have an output value can have multiple instances.  This includes Validation (warning text), Title (title text), Calendar (color value), etc.
