### ISSUE TITLE
5.4.4 iOS:  List configured default value not display when select value from list

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#151]
Log into the app as user rkromer
Create Service Request select Equipment list of values
Select value from list
The equipment code is displayed on the form attribute when it should display the equipment description.

App ID:  service.taylorfreezer.net

5.4.4 (2228)
Does not occur on Andorid 5.4.5 (1109) release

**Comment by matthewtsmith** [comment]
Fixed in 5.4.5
