### ISSUE TITLE
Web:  Create New User fails with 502 error

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#153]
Create new user account
Display Name = Mellissa Tort
Username = mellissa.tort@apptreesoftware.com
Password enter value
Store No = CARNIVAL/CELEBRATION

Press REGISTER button and get the error:
Invalid response from connector with status 502

service.taylorfreezer.net
sandbox / beta

**Comment by johnpryan** [comment]
@matthew I'm trying to reproduce but I'm getting a 505 from the core, saying `{"message":"Invalid response from connector with status 404"}`

**Comment by mellissatort** [comment]
@johnpryan @matthewtsmith I updated the connector url (datasets/lists) in the sandbox beta version to use the Taylor Freezer connector url and not ngrok.  Is there another place this needs to be updated as well?  I'm noticing when I try to log in to the app ID that it still seems to be using ngrok url instead of Taylor Freezer connector url.  I am not finding any other spots in the portal to configure this.

**Comment by matthewtsmith** [comment]
The user connector needs to be updated.

**Comment by mellissatort** [comment]
@johnpryan I found the missing config for this connector and updated it to point to Taylor Freezer connector url.  Closing ticket.
