### ISSUE TITLE
Web:  Create new user UserName attribute has requirements for valid value that should be defined on the form

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#154]
Created a new user with username "mellissa.tort" and received an error that the username value was not valid.  Updated the username to "mellissa.tort@apptreesoftware.com" and the user registration completed successfully.  There appear to be criteria for a valid username value.  These should be defined on the form for user reference when they are creating a new user account.

service.taylorfreezer.net
sandbox / beta

**Comment by johnpryan** [comment]
This is because the username field is an "email" type.   You can configure it to be a text field if necessary.

**Comment by mellissatort** [comment]
@johnpryan what would be the easiest way to let the user know the value they enter should be an email address?  Sometimes with user registration forms when you create an account for the username field they have help text in the text field saying something like "enter email address".  Can we do something like that on this form?

**Comment by johnpryan** [comment]
Here's one solution:

![email](https://cloud.githubusercontent.com/assets/1145719/19986221/0e153fd6-a1d3-11e6-8c6d-f06b3b7975ce.gif)

But I think it's a bit jarring.

Maybe we should consider configuring the title to just say "email"?

**Comment by matthewtsmith** [comment]
@johnpryan @mellissatort I think we should go with @johnpryan suggestion that the title should say "Email/Username" or "Username ( Provide email address)"

**Comment by mellissatort** [comment]
@johnpryan @matthewtsmith I have updated the user registration form display name for the Username field to be "Username (Provide Email Address)".  Closing ticket.
