### ISSUE TITLE
Portal/Core:  Default Value "User: Name" no longer is valid and has to be changed to "User: Display Name"

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#156]
Create Service Request Page Configuration:  http://sandbox.apptreesoftware.com/#/app/service.taylorfreezer.net/beta/builder/device/page/3586

The "Requestor" attribute was previously configured with default value "User: Name" but this is no longer a valid value.  It must be changed to "User: Display Name".  We will have to go into each customer configuration using this and change it from Name to Display Name.  I'm unsure how many configurations this affects in R5.

App ID:  services.taylorfreezer.net
sandbox / beta

**Comment by sambbaron** [comment]
@matthewtsmith @mellissatort I can deploy a Portal that converts `$runtimeContext.user.Name` to the attribute index equivalent of `$runtimeContext.user.displayName`.

**Comment by matthewtsmith** [comment]
@sambbaron would we still have to go through and update all of the configs?

**Comment by sambbaron** [comment]
@matthewtsmith @mellissatort If this is only effecting default values, then I could implement a solution that would update all default values on initial builder load.  You would not have to open each display element separately.

**Comment by mellissatort** [comment]
@sambbaron When I change the default value from "Name" to "Display Name" and save it doesn't seem to be committing the save.  When I go view the default value again the description in the field indicates Display Name is now being used but when I click on it Display Name is not the selected attribute type.  Also, when I view this form in the client (5.4.5 (2237)) I do not see the default value for Requestor.  I do see it for Store No and Customer No though.

**Comment by sambbaron** [comment]
@mellissatort I will look at this as I am working on the global fix

**Comment by matthewtsmith** [comment]
@sambbaron What about just leaving it as "Name"? Is there a strong reason to change it?

**Comment by sambbaron** [comment]
@matthewtsmith It doesn't matter to me.  The issue is that `Name` is not an attribute name in the user dataset.  The portal is just comparing the old user key string to the new dataset attribute name.  I guess we could have fixed this in the connector, but I've already deployed the fix to portal sandbox.  

@mellissatort Fix deployed to portal sandbox `0.8.0-dev.36.6`

**This also fixes the bug Mellissa mentioned when the user attribute is being lost on selection**

**Comment by matthewtsmith** [comment]
@sambbaron so what is the process that @mellissatort has to do to update configurations? I'm not clear on that from this discussion.

**Comment by sambbaron** [comment]
@matthewtsmith All @mellissatort has to do is open the app in the builder and click `SAVE`.

**Comment by matthewtsmith** [comment]
@mellissatort This will cause a configuration update which means we will definitely have to communicate an outage and that all work should be submitted prior to the outage window.

**Comment by sambbaron** [comment]
@matthewtsmith If you would prefer to fix this in the connector, I am fine with rolling back my change.

**Comment by mellissatort** [comment]
@sambbaron is it possible to have a fix for this that does not require me to go into the builder and click Save?

**Comment by sambbaron** [comment]
@mellissatort It couldn't be a Portal fix.

@matthewtsmith ?

**Comment by matthewtsmith** [comment]
@mellissatort After more thought, I believe this ONLY applies to Taylor Freezer because they are the only one using the new SDK and that is what has changed to`DisplayName`. I don't even remember where the original `Name` came from. @sambbaron was that a hard coded user value we have before?

**Comment by sambbaron** [comment]
@matthewtsmith I assume so.  I would have gotten it from the Core.

**Comment by mellissatort** [comment]
@sambbaron @matthewtsmith since it is Taylor Freezer only this is not a big deal for go live deployment
