### ISSUE TITLE
5.4.5 Client:  Default Value "Display Name" not visible on client form

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#158]
Create Service Request form has Requestor default value "Display Name" configured.
When I log into the app as user mellissa.tort@apptreesoftware.com the display name value is not displaying on the form for the Requestor field.
Other default value such as customer no and store no are displaying on the form.

App ID:  service.taylorfreezer.net
sandbox / beta

iOS 5.4.5 (2237)
may exist on android as well but unable to test that right now.

**Comment by mellissatort** [comment]
@matthewtsmith Issue exists on Android client as well (5.4.6 1112)

**Comment by matthewtsmith** [comment]
iOS Fix: https://github.com/apptreesoftware/apptreerevolution-ios/commit/74f69f3a579fb8f1fe80c98936a72d85e88906cd

**Comment by matthewtsmith** [comment]
Fixed by: https://github.com/apptreesoftware/apptreerevolution-android/commit/aece289400756787e5fcc1082c9e2179b0ac11e1
