### ISSUE TITLE
Create User:  Created new user Debbie Smith and Display Name not populated correctly

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#161]
Created new user with display name "Debbie Smith" and username "tortmel@yahoo.com".
Returned to the login screen and username was prepopulated.
Entered password and pressed login.
Because the app was in beta mode the login failed because the user is not setup as a beta tester.
Logged into sandbox portal and edited the user Debbie Smith.
The username, email and display name all show the value "tortmel@yahoo.com"
The display name should show the value "Debbie Smith"
Add value "Debbie" to first name field
Add value "Smith" to last name field
This then updates the display name to "Debbie Smith"
Set is beta tester to true and save changes.

App ID:  service.taylorfreezer.net
sandbox / beta

**Comment by sambbaron** [comment]
@mellissatort So the values you entered into the user registration form from the web client were not what was set in the new user?  Then you used the Portal to fix it.  Could be a problem with the web client.  I am assigning to @johnpryan.

**Comment by mellissatort** [comment]
@sambbaron @johnpryan Yes the Display Name entered on the registration form did not populate into the Display Name field on the portal.  Username populated there instead.  I had to manually fix it in the portal.

**Comment by matthewtsmith** [comment]
@johnpryan Assigning to me, I'm guessing this is a core bug.

**Comment by matthewtsmith** [comment]
@johnpryan Blocked by https://github.com/apptreesoftware/revolution/issues/160

**Comment by mellissatort** [comment]
@matthewtsmith The display name is still not displaying properly in the Portal under App Users when I edit a user.  Attached is a screenshot of the user edit form for a new user I just created.  On the App Users list the name "Brian T Tort" displays but in the user edit form it does not.
<img width="902" alt="screen shot 2016-11-04 at 1 28 58 pm" src="https://cloud.githubusercontent.com/assets/22403044/20015770/1fe9b366-a293-11e6-8b6c-3aadf1115e59.png">

**Comment by matthewtsmith** [comment]
@mellissatort this was not supposed to be closed, sorry about that.

**Comment by mellissatort** [comment]
@matthewtsmith some more information that may help in troubleshooting this.  As I mentioned on the App Users list the display name is listed "Brian T Tort" and in the edit user form it is "brian.tort@effcomp.com".  I made no changes to the user attributes other than setting the user to beta tester and saved the changes.  The display name now on the App Users list is "brian.tort@effcomp.com".  It's as if at some point it knows what the display name should be but then gets something confused when writing it to the portal edit users form.

**Comment by sambbaron** [comment]
@matthewtsmith @mellissatort There is a portal bug that is overwriting the display name in the user editor.  The display name looks correct in the Core.  I am working on it now.

**Comment by sambbaron** [comment]
@mellissatort Fix deployed to portal sandbox `0.8.0-dev.36.12`

**Comment by mellissatort** [comment]
confirmed fixed
