### ISSUE TITLE
Portal:  User details should not require first name and last name

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#162]
When a new user is created from the user registration process the user does not exist in portal with a first name and last name value.  These fields should not be required in the Portal when editing user details.

http://sandbox.apptreesoftware.com/#/app/service.taylorfreezer.net/app-users

App ID:  service.taylorfreezer.net
sandbox / beta

**Comment by sambbaron** [comment]
@mellissatort This has been deployed to portal sandbox `0.8.0-dev.36.7`

**Comment by mellissatort** [comment]
Confirmed fixed.
