### ISSUE TITLE
Portal:  User Registration form list items unable to configure list display options

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#164]
Select User Registration page configuration.
http://sandbox.apptreesoftware.com/#/app/service.taylorfreezer.net/beta/builder/device/page/registration
Select Store No attribute which is configured as a select list.
Unable to configure list display options for attribute.

This may be related to issue #163 

App ID:  service.taylorfreezer.net
sandbox / beta

**Comment by mellissatort** [comment]
@sambbaron This is also related to issue #166

**Comment by sambbaron** [comment]
@mellissatort Fix deployed to portal sandbox `0.8.0-dev.36.10`

**Comment by mellissatort** [comment]
@sambbaron There is now a + button next to Attribute Sorting in the list display options but when I select it I am unable to add attributes.  A warning message displays "Please select all sort attributes before adding new ones"

**Comment by sambbaron** [comment]
@mellissatort Fix deployed to portal sandbox `0.8.0-dev.36.11`

**Comment by mellissatort** [comment]
@sambbaron I configured attribute sorting for user registration form Store No attribute so that it sorted by Name.  Saved the configuration and then returned to view it and the attribute sorting did not save.  I tried this a couple times with every time it doesn't appear to save.  The client is not showing the sort either.

**Comment by sambbaron** [comment]
@mellissatort Fix deployed to portal sandbox `0.8.0-dev.36.13`

**Comment by mellissatort** [comment]
@sambbaron I was able to add attribute sorting but when I viewed the Store No list it is not using the sorting I setup.  I'm not sure if this is still your issue.

**Comment by sambbaron** [comment]
@mellissatort The configuration looks correct to me.  Let's have @matthewtsmith have a look at this.

**Comment by matthewtsmith** [comment]
@mellissatort @sambbaron this would be a web client thing. Assigning to @johnpryan
