### ISSUE TITLE
Portal:  User Connector configuration is not obvious on Security Settings

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#165]
A user connector configuration exists for the app ID, however it is not obvious from the portal display.
http://sandbox.apptreesoftware.com/#/app/service.taylorfreezer.net/security
User must select the Edit button next to "User Connector" to see that it has been configured.
Some type of information display should be visible on the main security settings screen, possibly the user connector name and url.  The user would then need to click the existing Edit button to modify.

App ID:  service.taylorfreezer.net
sandbox / beta

**Comment by sambbaron** [comment]
@mellissatort Fix deployed to portal sandbox `0.8.0-dev.36.10`

**Comment by mellissatort** [comment]
Confirmed user connector url is visible on Security Settings.  closing ticket.
