### ISSUE TITLE
5.4.5 iOS:  Adjusting duration dial minutes to 0 resets hours to 0

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#168]
Log into the app as vrodri2
Select work order W620566 from My Work Orders workbench
Start Timer
Let the timer run for 15 seconds
Stop Timer "I'm Done, Stop Time Clock"
On the New Time Entry page select the Hours field to adjust the time.  Currently hours display as 0:00
On the duration dial change minutes to 15 (hours is 0)
On the duration dial change hours to 1 (minutes remain 15)
On the duration dial change minutes to 0, hours then automatically change to 0.  Hours should have remained as 1.
*This issue does not appear to exist in Android

Navigate to Timecard menu
Select date 10/26/2016
Select time entry for work order W621215
Select the hours field.  Hours currently displayed as 2:00, and duration dial is set to "+ 0 0"
On the duration dial change minutes to 15 (hours is 0)
On the duration dial change hours to 1 (minutes remain 15)
On the duration dial change minutes to 0 (hours remain 1)
If possible the duration dial when launched should display the hours/minutes for the field value and not default to 0/0
*This exists in iOS and Android

App ID:  trial.uchc.edu
sandbox

iOS 5.4.5 (2237)
Android 5.4.6 (1113)

**Comment by matthewtsmith** [comment]
Fixed in 2240
