### ISSUE TITLE
Unable to view or add display element to create form

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#17]
App ID:  dev.usc.edu

Create New Cart:  http://portal.apptreesoftware.com/#/app/dev.usc.edu/beta/builder/device/page/1860

Select "Add Display Element" from drop down list for unnamed feature group.
New Display Element popup window is blank.  Same behavior exists when editing existing elements on the form.  I was able to view these 30 minutes ago without an issue.  No updates have been made to the connector configuration.

<img width="1381" alt="screen shot 2016-10-03 at 3 53 29 pm" src="https://cloud.githubusercontent.com/assets/22403044/19051788/3b4141f8-8982-11e6-8eb5-fd8fa8bed153.png">

**Comment by mellissatort** [comment]
@sambbaron I am using Chrome browser and having this issue with other forms and even other app IDs.  I tried this on Safari and am not having the issue.

**Comment by sambbaron** [comment]
@mellissatort I am unable to replicate this issue.  However, I think it might be related to me deploying the portal.  I don't have a great solution to this right now.  I could end all portal user sessions via the Core, but this would not logout the portal user until you tried to make a call to the Core.
