### ISSUE TITLE
Portal:  When session times out and log back in cannot select "To Dashboard"

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#174]
When portal session times out I am returned to the portal login screen.
I log in as apptreedev and am returned to the page I was timed out from.
I attempt to click on the "To Dashboard" button but it does not do anything.  I am able to select other menu options within the current app ID.

If I refresh the browser then I am able to click on the "To Dashboard" button and the app ID dashboard page displays.

I am using Chrome.

**Comment by sambbaron** [comment]
@mellissatort Fix deployed to portal sandbox `0.8.0-dev.36.15`

**Comment by mellissatort** [comment]
confirmed fixed.  closing ticket
