### ISSUE TITLE
Web client not using message/showAsAlert from data set response

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/revolution#176]
When a form is submitted the connector will response with
```JSON
{
    "success": true,
    "message": "Successfully created request Wayfai5189",
    "showMessageAsAlert": true,
    "totalRecords": 0,
    "numberOfRecords": 0,
    "moreRecordsAvailable": false,
    "records": []
}
```

The web client should use the message from the response to display upon a form submission.
If showMessageAsAlert = true, it should show the message as an alert rather than a toast.

Repro: 
servicemaster.corrigo.com
login as `matthew`
Fill out form and submit

**Comment by matthewtsmith** [comment]
@johnpryan need this for tomorrows demo.

**Comment by johnpryan** [comment]
https://github.com/apptreesoftware/apptreerevolution-web/pull/81 should fix the issue but I can't test it until the corrigo connector is back up

**Comment by johnpryan** [comment]
^ showAsAlert is working in the corrigo app
