### ISSUE TITLE
5.4.5 Client:  Parts list is not downloading successfully

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#178]
Log into the app as rkromer
Select Order Parts menu item
Select + to add part items to order
Select Parts list.  List will download and then fail with "List download failed.  An unknown error occurred".

Testing url:  https://tfs15.taylorfreezer.net:9000/list/part/describe returns java describe.  See attached.

<img width="982" alt="screen shot 2016-11-07 at 4 57 51 pm" src="https://cloud.githubusercontent.com/assets/22403044/20077684/5cb00a50-a50b-11e6-91e2-9ad5e52264e4.png">

App ID:  service.taylorfreezer.net
sandbox

Android 5.4.6 (1115)
Unable to test on iOS at this time due to requestor Display Name not populating error.

**Comment by matthewtsmith** [comment]
@mellissatort I'm unable to repro this. Can you still get it to occur? If so, I may want to see the logs on your device via screen share.

**Comment by mellissatort** [comment]
@matthewtsmith This morning the parts list is displaying without issue.  I'll keep an eye on this throughout the day to see if the issue from yesterday reoccurs.
