### ISSUE TITLE
5.4.5 Client:  Store list displays result record lines but no data

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#179]
Navigate to create user account registration form.
Select Store No attribute to display list.
When list displays there are only record place holder boxes displayed and no data.

Confirmed in the form configuration the list is configured with custom display options where name is to be displayed in the list.

App ID:  service.taylorfreezer.net
sandbox

iOS 5.4.5 (2240)
Android 5.4.6 (1115)

**Comment by johnpryan** [comment]
I noticed this too - I think it's because those list items don't have a value.   If you scroll down you can see some list items with values.

**Comment by matthewtsmith** [comment]
@mellissatort I agree with John. It looks like that attribute is empty for quite a few records. If you scroll down there are lots more records with that attribute filled out. What we may want to do in the connector is check if that attribute is empty and if it is just use the `value` of the list.

**Comment by mellissatort** [comment]
I fixed the store list by removing those without a name and now it looks correct when displayed.  closing ticket
