### ISSUE TITLE
User Registration form Store list not returning results after updating connector list attributes

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#183]
Added attribute Post Code to the Store list
Refreshed the store list from connector.
Navigated to the User Registration page
Updated the Store No attribute list display options to include Post Code.
Tested the form in the client and store list never returns results.
Updated the list display options back to only displaying Name and retested client with same results store list never returns results.

Added select list to Create Service Request page configuration for attribute Store No.  Made the attribute editable and with list display options to include Name and Post Code.  Tested the Create Service Request form on the client and the store list returns results successfully with the correct display format.

App ID:  service.taylorfreezer.net
sandbox / beta

**Comment by mellissatort** [comment]
@johnpryan I updated the list configuration to be a public list and now the list displays properly on the user registration form.

**Comment by johnpryan** [comment]
https://github.com/apptreesoftware/apptreerevolution-web/pull/86 should ensure that a dialog is displayed indicating that an authorization exception happened
