### ISSUE TITLE
STANFORD : New list available on builder after few hours later

### ISSUE THREAD

**Issue by eyuapptree** [apptreesoftware/revolution#19]
AppID : lbredev.stanford.edu / somdev.stanford.edu
I added a new server site list list/searchavailablewo to the connector, But no mater how I refresh from connector, or deploy connector again and again, or  quit the builder/brower and then come back. The new list was not available on builder. But after few hours later, when I came into builder again, I can see it there. there seem to be some kind of delay.

**Comment by eyuapptree** [comment]
Currently it is not an issue because  the new list I needed is available now.  But I wait few hours after deploy and finally see it available on builder.

**Comment by matthewtsmith** [comment]
@alexisandreason I think we have a bug with user based lists that needs to be investigated.
