### ISSUE TITLE
5.4.5 Staging:  Unable to load store list on user registration form

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#190]
Select Create User Account link.
Select Store No field to display list.
First time the field is selected the list attempts to load and fails.
Second time the field is selected it immediately results in "Failed to load list."

This is occurring on iOS and Android

App ID:  service.taylorfreezer.net
branded app as well as unbranded app (sandbox)

In branded app, enter zip code 97209 to be directed to service.taylorfreezer.net app ID

iOS 5.4.5 (2242)
Android 5.4.6 (1118)

**Comment by johnpryan** [comment]
I'm having trouble reproducing this.  If I go to http://go.apptreesoftware.com/#/user/register?core=https://services-sandbox.herokuapp.com&app=service.taylorfreezer.net&redirect=http://google.com/&beta=true or the non-beta version http://go.apptreesoftware.com/#/user/register?core=https://services-sandbox.herokuapp.com&app=service.taylorfreezer.net&redirect=http://google.com/&beta=true I am able to load the store list

**Comment by mellissatort** [comment]
Updated the store list to "Search" list fetch type and verified list was checked as public.  Now able to display store list.
