### ISSUE TITLE
Portal:  Unable to select custom user attribute on user registration form

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#195]
Created new user attribute "Postal Code" in Security Settings (attribute 30).
Navigated to the user registration form and the new attribute is not available to select to add to the form.
Alexis indicated that custom attributes are being created with the create and update flags automatically set to false from the portal.  Can this be configurable?

http://portal.apptreesoftware.com/#/app/service.taylorfreezer.net/beta/builder/device/page/registration

App ID:  service.taylorfreezer.net
beta

**Comment by sambbaron** [comment]
@mellissatort Fix deployed `0.8.2`

**Comment by sambbaron** [comment]
@mellissatort You'll need to save the security settings for the attribute flags to be set

**Comment by mellissatort** [comment]
@sambbaron I added a new attribute "Zip Code" to the Security Settings and saved the configuration.  I then went to the user registration form to see if I could add this new user attribute and it was not listed.

**Comment by sambbaron** [comment]
@mellissatort There is a Portal bug here, but if you refresh the page, you can see the new custom attribute.

**Comment by mellissatort** [comment]
@sambbaron I confirmed it is now displayed.  closing ticket.
