### ISSUE TITLE
Create Label + Checkbox template - Numeric ID 2

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/revolution#20]
Starting with the new checkbox template which should have the ID of 13.

**Comment by sambbaron** [comment]
@matthewtsmith I just realized that I already created this.  The key is `EDITABLE_TITLE_CHECKBOX` and it's the last template in the dropdown.  Do you want me to make any changes to this template?  Should I change the key to `2`?

![screen shot 2016-10-05 at 11 08 21 am](https://cloud.githubusercontent.com/assets/10456742/19125476/0d0c6220-8aec-11e6-8aaa-240d727951aa.png)

**Comment by matthewtsmith** [comment]
@sambbaron I just want to change the key to `2`

**Comment by sambbaron** [comment]
@matthewtsmith  Deployed to sandbox
