### ISSUE TITLE
User Registration:  Store list returning error "Failed to load list"

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#201]
When creating a new user on the user registration form the error "Failed to load list" is returning when selecting the Store list attribute.

Display Name:  Mel Tort
Username:  mellissa.tort@apptreesoftware.com
Password:
Enter Postal Code:  21845
Select Store attribute and message displays.

service.taylorfreezer.net
services1 (live)

TestFlight release
iOS 5.4.5 (2246)

**Comment by johnpryan** [comment]
As mentioned in Slack, I think the issue is the list is not a 'search' list and is not a public list.  I made those changes to the beta configuration and it seems to be working now.

**Comment by mellissatort** [comment]
Confirmed fixed
