### ISSUE TITLE
Taylor Branded Android:  Create Service Request - Equipment "No list available"

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#205]
Create Service Request
Select Equipment attribute list
Error displays "No list available.  A list has not been associated with this form element"

service.taylorfreezer.net
Taylor branded app - Android only

Android 5.4.6 1124

**Comment by matthewtsmith** [comment]
@mellissatort I can't repro this. My guess is that the list hadn't downloaded yet and we are not provided a better message to describe the issue. Can you check to see if this works for you now? If so, I will file a separate ticket to improve the error messaging.

**Comment by mellissatort** [comment]
@matthewtsmith I'm still having the issue on my device.  I have closed the app and relaunched it and the issue with the list still remains.

**Comment by mellissatort** [comment]
@matthewtsmith I'm testing android 5.4.6 (1126) branded Taylor Freezer app and I'm still having this issue, but I am finding that no lists are displaying in the android app.  Testing iOS app store build 5.4.5 (2246) the lists do display.  I looked at S3 Manager (All Buckets / services1-storage / lists) and the app ID services.taylorfreezer.net is not listed.  Where can I find the lists that this branded app is using to validate they are being generated?

**Comment by mellissatort** [comment]
confirmed issue is fixed
