### ISSUE TITLE
Can not create new "update and display records" feature

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/revolution#209]
Sandbox
inspect.corrigo.com
http://sandbox.apptreesoftware.com/#/app/inspect.corrigo.com/beta/builder

Upon trying to save the feature the console throws an exception and nothing happens. I'm trying to create a feature against the WorkOrder data source.

<img width="1853" alt="screen shot 2016-11-17 at 4 04 11 pm" src="https://cloud.githubusercontent.com/assets/9000800/20413058/88413d02-acdf-11e6-82ba-5eec21e9358c.png">

**Comment by matthewtsmith** [comment]
@sambbaron I did the same thing in production and it worked fine so it must be a recent sandbox change.

**Comment by sambbaron** [comment]
@matthewtsmith I deployed the fix to sandbox `0.8.7-0.9.0-dev.5`
