### ISSUE TITLE
Add `order` value to templates

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/revolution#21]
On the client I am revamping the template system. To help me validate I'm ordering the fields right I would like to add the `order` to the template view. Something like the attached image.
<img width="479" alt="screen shot 2016-10-04 at 7 00 39 pm" src="https://cloud.githubusercontent.com/assets/9000800/19098794/178196ee-8a65-11e6-9e5e-795e9f3bb455.png">

**Comment by matthewtsmith** [comment]
@sambbaron This is something I'd like you to work on tomorrow so I can validate everything on my end.

**Comment by sambbaron** [comment]
@matthewtsmith I don't understand what you are asking of me.  Are we validating the client against the builder or vice versa?  Do you want me to create screenshots of all the current templates with order values as they are in the builder?

**Comment by matthewtsmith** [comment]
Im asking you to add the order into the template in the builder UI. We will consider the builder the "truth" of what the order should be.  As I'm redoing these templates I will use that order on my templates. Going forward I think this will be useful as we add new templates so that there is no confusion about the attribute ordering on new templates.

**Comment by sambbaron** [comment]
@matthewtsmith Ah sure, that's no problem.  I will only show the values when the Builder is in "debug mode" (which is all the time right now).

**Comment by sambbaron** [comment]
@matthewtsmith This is deployed to both portal and sandbox

**Comment by matthewtsmith** [comment]
@sambbaron Glad we did this, some of your order indexes are a lot different than mine.

**Comment by sambbaron** [comment]
@matthewtsmith Yeah, that's not a surprise, especially for the older templates.  Maybe we can finally put this zombie bug to rest.
