### ISSUE TITLE
Unable to add DisplayElement to existing form

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/revolution#210]
http://sandbox.apptreesoftware.com/#/app/inspect.corrigo.com/beta/builder/device/page/4109

In the feature group tap "Add Display Element"
Choose any attribute ( I chose "Documents" )
Click add.

Exception is thrown in the console

**Comment by sambbaron** [comment]
Fix deployed to sandbox portal `0.8.9-0.9.0-dev.6`
