### ISSUE TITLE
Unable to configure Date fields properly

### ISSUE THREAD

**Issue by alexisandreason** [apptreesoftware/revolution#212]
**Description**
I have two fields whose data type is Date but in the portal the only type of data element I am allowed to choose from the drop down is Date Range
**Steps to Reproduce**
Go to ccsstage.famis.com
Navigate to search work orders menu item in the beta version
The last two items are complete date from and complete date to, the data set attributes those fields are linked to have a type date but the only option for the data element is date range
**App ID**
ccsstage.famis.com
**Version Number**
4

**Comment by sambbaron** [comment]
@alexisandreason Closing this ticket per Matt's explanation that on a search form, a date attribute can only have a "date range" display type.
