### ISSUE TITLE
Unable to delete a feature group

### ISSUE THREAD

**Issue by alexisandreason** [apptreesoftware/revolution#216]
**Description**
I am unable to delete a feature group from a feature.
**Steps to Reproduce**
Click on a feature groups dropdown
click 'Edit Feature Group'
click 'remove' and 'yes' buttons to confirm
notice the feature group is still there
**App ID**
ccsstage.famis.com
**Version Number**
beta version

**Comment by sambbaron** [comment]
@alexisandreason What feature group you are trying to delete?  
Also for Portal github issues, please copy the url into the issue description.  That will give me the app ID, version, etc.

**Comment by sambbaron** [comment]
@alexisandreason I deployed the fix to `0.8.12`
