### ISSUE TITLE
5.4.6 Android:  New time entry comments clears when press Submit

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#218]
Log into the app as user jlw8
Select work order from My Work Orders workbench
Start timer
After approximately 1 minute stop timer.  You are redirected to the "New Time Entry" form.
Adjust the hours to 15 minutes
Enter comment "Test"
Press the Submit button.  The comments entered are cleared and error message displays that comments are required.
*NOTE*  I was able to make this occur two times in a row.

Re-enter comment "Test"
Adjust the hours to 1 hour 15 minutes
Press the Submit button.  The change saves successfully.

*NOTE*  I was not able to make the error re-occur after completing the above three steps

App ID:  feandpdev.rice.edu
Staging

Android 5.4.6 (1126)

**Comment by matthewtsmith** [comment]
@mellissatort This is because we buffer the input at 1 second so that the criteria system doesn't run while you type. If you type fast enough and press submit this can happen. I've removed that throttle. If you notice any delays while you're typing let me know and I can add small delay back in.

**Comment by matthewtsmith** [comment]
I've reduced the delay to 100ms

**Comment by mellissatort** [comment]
confirmed issue is fixed
