### ISSUE TITLE
Missing LEFT_IMAGE_6_ATTRIBUTE_GREY_BOTTOM template

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/revolution#22]
@sambbaron Possibly it's named different but I'm not seeing this template

**Comment by sambbaron** [comment]
I think it's this - `CARD_CENTER_IMAGE_6_ATTRIBUTES`

**Comment by matthewtsmith** [comment]
@sambbaron No, thats not it. I have another one for that. LEFT_IMAGE_6_ATTRIBUTE_GREY_BOTTOM  is something we did last minute for wawa. Maybe it never made it into 5.4

**Comment by sambbaron** [comment]
@matthewtsmith Can you give me a screenshot from the client?

**Comment by matthewtsmith** [comment]
![simulator screen shot oct 5 2016 9 29 34 am](https://cloud.githubusercontent.com/assets/9000800/19122238/5cd7636c-8ade-11e6-966f-af83d7749076.png)

**Comment by matthewtsmith** [comment]
@sambbaron This isn't the greatest sample since there are some labels not used in wawa. You may want to look at 5.3 portal for all the labels.

**Comment by sambbaron** [comment]
@matthewtsmith I don't think I have this template.  I don't see any templates in the Builder with an image on the left side.

**Comment by matthewtsmith** [comment]
@sambbaron ok, lets add it then. Here is a screen shot of how it is setup on the client.  You define the order and I'll update.

<img width="672" alt="screen shot 2016-10-05 at 9 47 16 am" src="https://cloud.githubusercontent.com/assets/9000800/19122773/d272a170-8ae0-11e6-9e8e-d9820bbac574.png">

**Comment by sambbaron** [comment]
@matthewtsmith Do you want to start the numeric ids with this template?  If so, which number?
https://github.com/apptreesoftware/revolution/issues/20

**Comment by matthewtsmith** [comment]
@sambbaron I set the editing checkbox template as 13. We could make this 12 since its taking the place of one of the templates I counted. Or we could just decide to start these at 1 which might be easier. Thoughts?

**Comment by sambbaron** [comment]
@matthewtsmith I don't have a strong opinion, but my preference would be to stay with the semantic names.  I know they are cumbersome, but at least they give the template some transparent meaning.  I guess it depends on how many more templates we will have before moving to the new templating system.  If it's 10 templates, I'm fine with semantic keys.  If more than 10, then maybe numbers.  Like I said, I don't have a strong opinion on this.  If we are starting the numbering system, I say start with `1`.

**Comment by matthewtsmith** [comment]
@sambbaron I would like to switch to numbering, lets start with `1`. I find it very cumbersome to find the template in my code that matches the name in the builder. Numbering would make this much easier on the clients. 

So in conclusion:
`LEFT_IMAGE_6_ATTRIBUTE_GREY_BOTTOM` => 1
`Label + Edit Checkbox` => 2

**Comment by sambbaron** [comment]
@matthewtsmith Here's what this template is going to look like - not deployed yet

![screen shot 2016-10-05 at 11 02 04 am](https://cloud.githubusercontent.com/assets/10456742/19125388/b45d1674-8aeb-11e6-8610-ebb862110ae8.png)

**Comment by sambbaron** [comment]
@matthewtsmith Deployed to sandbox
