### ISSUE TITLE
Link pages are not working

### ISSUE THREAD

**Issue by alexisandreason** [apptreesoftware/revolution#222]
**Description**
In the ccsstage app, I created the feature called 'My Work Orders'. I then created 'My PM Work Orders' and tried to reuse the features from the first one. The new pages that reused the features were not included in the pages array to the core, so the link page is broken. It also doesn't create the page when I try to update it. 
**Steps to Reproduce**
Go to the ccsstage.famis.com app
navigate to my PM work orders (http://portal.apptreesoftware.com/#/app/ccsstage.famis.com/beta/builder/device/page/4129)
click on the feature group to edit it
try to add the feature group 'My Work Orders Detail' in the linked page
click save on the modal and then save the configuration
notice that the link page is gone
-- I included the request object from the config update. If you look in the pages array the ones that should have been created with negative IDs are not there.
**App ID**
ccsstage.famis.com
**Version Number**
14
[configSaveObject.txt](https://github.com/apptreesoftware/revolution/files/607220/configSaveObject.txt)

**Comment by alexisandreason** [comment]
@RobertGuinn FYI

**Comment by sambbaron** [comment]
@RobertGuinn @alexisandreason  Fix deployed to `0.8.14`
