### ISSUE TITLE
User values are not being used in the client

### ISSUE THREAD

**Issue by alexisandreason** [apptreesoftware/revolution#224]
**Description**
I have a server filter for my work orders that should fill the value with $runtimeContext.user.3 (which is the username) but it is not working. It also isn't working when I use the same value as a default for a form element.

**Steps to Reproduce**
Go to ccsstage in portal, navigate to data connectors, accruent cloud connector, and My Work Orders dataset
Click to view/edit the server filters and notice AssigneeID is set to use $runtimeContext.user.3 (I've also tried to use $runtimeContext.user.username).
Go to the client, set it to beta mode, and login using credentials for jbarkelo in ccsstage in 1password. Notice that the AssigneeID header is not being sent in the URL param.
This is also the case if you navigate to a work order by searching, clicking the dropdown button menu and add labor entry. The employee field is empty but it is also configured to use the same user value.

**App ID**
ccsstage.famis.com

**Version Number**
beta version 14

**Comment by matthewtsmith** [comment]
@alexisandreason When I debug this on iOS it seems to be working as expected. Here is the cURL that is getting produced. AssigneeId=22

```curl -i \
	-H "Accept-Language: en;q=1.0" \
	-H "User-Agent: AppTreeRevolution/5.4.6 (com.apptreesoftware.revolution; build:DEV; iOS 10.1.0) Alamofire/4.1.0" \
	-H "X-APPTREE-VERSION: 14" \
	-H "X-APPTREE-DEVICE-ID: CC11B899-935C-4A86-8DD2-28CE008E81CA" \
	-H "Accept-Encoding: " \
	-H "Authorization: Basic amJhcmtlbG86MTUzMzgz" \
	-H "X-USERNAME: jbarkelo" \
	-H "X-APIKEY: ClmWLaNbfy5VFKoOTqBnXRnpPg9EqRkKEkjkAAUGnuQE4inuHbKfqdkfXi1TPZ+/BLq8BQiLgyQjiGbHkeqy/gsatgrjUSMesw0bUWMl1ePJAdWot3O2xh+9QV3+wmBgbOZ0OAnXoyObWGE3O+8poev9mre/PShG4vqrJNY6LQWEFPaTHoHd180JS4p52OCeqlFja2Cgi+/mIm+cMRzv9DD0ALhBWMgKgz2Ron7x/X4718T7vXy5CqAGmHsq24Kb02PXvOVo3LC3HmfpOhEua2tMnBOY+GpC" \
	-H "X-Auth-Token: ATLASAUTH2=C40EAB2439A52EB7757AA20112EA59E2648A73C402A69D4F9F9C8DFCF6B3F2F17A88961316E87761737EDA51A3C517C423B10C49C8BCB4E1EFABE953417F327FBC712FDA9A9E08BDBF732E8986B9987DB0DF266879BC3E2792D12B11F6B4E816F6BD9340174588AD480A5D4AFEA4C13E508E37C1058E22A246B4D4FCCD76E858DB3EE5D7FA7D06FA30302D60799036509C5CC94C392447BEC857C524C629AB453D6B9052034AB3C19EC9FF588ECDE8EC03A1EA31911384A9DBD4F6B8E79E836775BB2FB5D285E9E9C79AF4C361F9CE42E481E3652A3817DC02A4F089CEF62195B18329FF7CFD5D1336ADD63DFACDEADF792C238DE8CE68808F6FF6900B09B655C1498844BA477506A1B5DC6AD2E456EEECF09F032EA43FA120F8996D5D3CAC8B519E3FBD; path=/; secure; HttpOnly" \
	-H "X-APPTREE-APPLICATION-ID: ccsstage.famis.com" \
	"https://services1.apptreesoftware.com/client/data/dataSet/1088?AssigneeID=22&WorkOrderOrigin=Reactive&offset=0&pageSize=0"```

**Comment by matthewtsmith** [comment]
@alexisandreason I'm also seeing the user get filled out on the Add Labor Entry.

What build are you using?

![simulator screen shot nov 23 2016 6 56 34 am](https://cloud.githubusercontent.com/assets/9000800/20566452/fe308432-b149-11e6-90b6-bae5586e3ec9.png)

**Comment by matthewtsmith** [comment]
@alexisandreason closing now that you are using the newer clients.
