### ISSUE TITLE
InheritedDataSetItem on subform using incorrect DataSet

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/revolution#225]
http://portal.apptreesoftware.com/#/app/refuse.uic.edu/beta/builder/device/page/4157

I'm trying to add a default value on a subform. When I choose Inherited Data Set Item the list of available options are from the current sub items data set and not the parents data set.

<img width="897" alt="screen shot 2016-11-23 at 11 05 08 am" src="https://cloud.githubusercontent.com/assets/9000800/20575155/f0272d96-b16c-11e6-8a99-c8fbdde224ee.png">

refuse.uic.edu

**Comment by sambbaron** [comment]
@matthewtsmith This logic has been set in the Portal for quite awhile (April), so I want to make sure I am clear on your expectation.  The Portal is using the linked object, in this case the relationship element, to determine the inherited data set.  But I am assuming that you are expecting the inherited data set to come from the parent page.  I'm surprised this hasn't come up sooner.

![screen shot 2016-11-25 at 7 25 44 am](https://cloud.githubusercontent.com/assets/10456742/20629840/70f323a0-b2e2-11e6-8fe5-027e96f84a01.png)

**Comment by matthewtsmith** [comment]
@sambbaron That is correct. I'm also surprised this hasn't come up sooner. Although, I think Mellissa has mainly been using this when going from an `update` form to a `New` form using a button. This is the case where I'm going to a sub form from a repeating element.

**Comment by sambbaron** [comment]
@matthewtsmith Fix deployed to `0.8.15`
