### ISSUE TITLE
Can not add new feature group to form

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/revolution#226]
I'm trying to add a new group inside the forms "Root Group" in order to logically group elements on the form. 

http://portal.apptreesoftware.com/#/app/refuse.uic.edu/beta/builder/device/page/4157

When I click "Root Group" -> Add new Feature group inside
I get a blank modal and I see that an exception has been logged in the console.

**Comment by sambbaron** [comment]
@matthewtsmith Fix deployed to `0.8.15`
