### ISSUE TITLE
5.4.3 (2151) On create form attach photo and values entered are cleared out

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#23]
App ID:  service.taylorfreezer.net
iOS Version:  5.4.3 (2151)  - app store download
User login:  rkromer

On Create Service Request form enter equipment and description values.  Then add a photo attachment.  After pressing the "Use Photo" option it returns the user to the form and the previous equipment and description values entered are cleared requiring the user to reenter them.

This issue is only occurring on iOS.  I tested with Android version 5.4.3 (1081) and the issue did not occur.

**Comment by mellissatort** [comment]
This was tested on iOS10 and iOS9 and both have the issue.

**Comment by mellissatort** [comment]
@matthewtsmith have you been able to look at this iOS client issue?

**Comment by matthewtsmith** [comment]
@mellissatort Fixed in 5.4.4
