### ISSUE TITLE
400 return on logo update

### ISSUE THREAD

**Issue by sambbaron** [apptreesoftware/revolution#235]
I am getting a 400 response on updating the branding logo.  I have tested both in services1 and sandbox.  The curl is from sandbox.

[curl.txt](https://github.com/apptreesoftware/revolution/files/625368/curl.txt)

**Comment by alexisandreason** [comment]
It looks like you are using the wrong format for sending the image. The core is expecting a file part with the label 'image'. I will attach an example curl. 
[exampleLogoSave.txt](https://github.com/apptreesoftware/revolution/files/625430/exampleLogoSave.txt)

**Comment by sambbaron** [comment]
@alexisandreason I don't understand. Did something in the Core change? I am sending `name="image"`

>------WebKitFormBoundary4SAawscEJuDZ0Vbj
Content-Disposition: form-data; name="image"; filename="attachment.png"
Content-Type: image/png

**Comment by alexisandreason** [comment]
@sambbaron No, nothing in the core has changed for branding in months. The content type should be multipart/form-data with a file part whose label is image.

**Comment by alexisandreason** [comment]
@sambbaron I'm looking back through commits to see if there was a change but I don't think there has been one. This sounds familiar though.

**Comment by sambbaron** [comment]
@alexisandreason I'm not sure what you mean by `label`.  I can send `name`, but not `label`.

**Comment by alexisandreason** [comment]
@sambbaron The label (or name) of the file part is image. Sorry, I think of those things somewhat interchangeably.

**Comment by sambbaron** [comment]
@alexisandreason No problem, so in that case, I don't see anything wrong with the object the Portal is sending.
