### ISSUE TITLE
Portal:  Unable to set default values on attribute

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#239]
http://portal.apptreesoftware.com/#/app/ppddev.uvm.edu/beta/builder/device/page/4239
Select Requestor attribute
Select + to add default value
Criteria editor does not allow me to select default value values.

ppddev.uvm.edu

**Comment by mellissatort** [comment]
@sambbaron also unable to configure Criteria on attributes, menu items, or buttons.  Similar behavior to what is seen with default value configuration wizard.

**Comment by mellissatort** [comment]
@sambbaron I'm also having and issue editing the data connector url.  I can select the field but I cannot type anything in it.

**Comment by sambbaron** [comment]
@mellissatort Fix deployed to `0.8.18`
