### ISSUE TITLE
Can not edit NamedFilter accessory view

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/revolution#246]
http://sandbox.apptreesoftware.com/#/app/refuse.uic.edu/beta/builder/device/page/4321

I've added an accessory view. I'm attempting to give it 3 segments:

To Do, Completed, Exceptions

The criteria is:

To Do
$dataSetItem.dataCollectionStatusString = NONE

Completed:
$dataSetItem.dataCollectionStatusString = COMPLETE

Exceptions:
$dataSetItem.dataCollectionStatusString = EXCEPTION

Because we have no concept of `dataCollectionStatus` in the portal yet I was attempting to just add this using manual input.

After saving the configuration none of the data was retained including the names of the segments. The NamedFilter still shows up on the page but it's name and criteria are empty when you go back to edit it.

**Comment by matthewtsmith** [comment]
@sambbaron not critical but I do need this fixed fairly quickly.

**Comment by sambbaron** [comment]
@matthewtsmith Are there going to be multiple dataCollection attribute types like this?  Should we have a group prefix like `$dataSetItem.dataCollection.statusString`?

**Comment by matthewtsmith** [comment]
@sambbaron Lets do `$dataSetItem.status`. We may be able to expand this attribute in the future for purposes outside of the data collector.

**Comment by sambbaron** [comment]
@matthewtsmith This has been deployed to both prod and dev portal `0.8.21`

**Comment by matthewtsmith** [comment]
@sambbaron This is still occurring. It lets me select the name filter criteria and enter a name but after I publish the configuration all the information clears.
