### ISSUE TITLE
WAWA 5.3.12:  Timer not visible on all user workbenches

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#25]
App ID:  vendor.wawa.com
iOS Version 5.3.12
Login:  demo3

Select work order 11721657 from "Work Orders - Unassigned" workbench and assign to logged in user Demo Three.
Start timer on work order
Make additional updates on work order including:
   1) add workcode (2 of them) and resolution code then submit
   2) add tag then submit
   3) remove resolution code then submit
Return to menu and timer is still running on profile.  Select timer and see work order listed.  Select work order and see button options include discard/pause/complete.
Return to menu and select "Work Orders - Assigned to Me".  Work order is not shaded gray to indicate timer running.  Work order details do not show timer running and buttons are not enabled to allow timer stop.
Return to menu and select "Search For My Company's WOs".  Select work order 11721657.  Work order is not shaded gray to indicate timer running.  Work order details do not show timer running and buttons are not enabled to allow timer stop.

The only way I can stop the timer is to select the running timer on the profile and the work order listed.

**Comment by matthewtsmith** [comment]
@mellissatort @RobertGuinn This is expected behavior. Since those are separate data sets there is no way to know that they are tracking on the same item. I think a more appropriate fix would be to not allow users to start timers from search or unassigned.
