### ISSUE TITLE
Card Layout 6 attribute Center Image template has duplicate order

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/revolution#27]
Order 2 is repeated for both "Above Image" and "Below Image"
<img width="488" alt="screen shot 2016-10-05 at 9 56 37 am" src="https://cloud.githubusercontent.com/assets/9000800/19123073/19f50a6e-8ae2-11e6-8251-dcdfbf45faf0.png">

**Comment by sambbaron** [comment]
@matthewtsmith This is what I am changing this template to - not deployed yet.

![screen shot 2016-10-05 at 11 04 26 am](https://cloud.githubusercontent.com/assets/10456742/19125330/889f9f84-8aeb-11e6-91c6-914c9adaec41.png)

**Comment by sambbaron** [comment]
@matthewtsmith Deployed to sandbox
