### ISSUE TITLE
Criteria: Unable to access relationship properties in criteria.

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/revolution#28]
http://sandbox.apptreesoftware.com/#/app/inspections.corrigo.com/beta/builder/device/page/3584

I'm attempting to configure a criteria for the following Feature->Exception Criteria

`IF ANY DataSetItem.uncommitted.punchListItems.exception IS NOT BLANK`

I don't see a way from the UI to configure that.  Here is a screen shot of my attempt.

<img width="910" alt="screen shot 2016-10-05 at 1 16 05 pm" src="https://cloud.githubusercontent.com/assets/9000800/19129979/3fc3e8ac-8afe-11e6-9784-3c97a18b2746.png">

**Comment by matthewtsmith** [comment]
@sambbaron marking as critical as its blocking my corrigo implementation.

**Comment by sambbaron** [comment]
@matthewtsmith Right now when we tack on a list attribute in criteria, we use this format:
`$dataSetItem.attribute.uncommitted.8.attribute.0`
I plan on using the same format for relationship attributes.

**Comment by sambbaron** [comment]
@matthewtsmith Deployed to sandbox - `0.7.0-dev.5`
