### ISSUE TITLE
Inspection Data Sources not displaying

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/revolution#32]
http://sandbox.apptreesoftware.com/#/app/inspections.corrigo.com/beta/data-connectors/545/data-sets/dataset-customerportal/new

`inspections.corrigo.com`
Data Sources

I have an Inspection Data source registered but the Inspection section is not displaying in the portal.

**Comment by sambbaron** [comment]
@matthewtsmith Fix deployed to sandbox - `0.7.0-dev.6`
