### ISSUE TITLE
STANFORD: Total daily hour not correct

### ISSUE THREAD

**Issue by eyuapptree** [apptreesoftware/revolution#33]
lbredev.stanford.edu
5.4.3.2173
![img_0231](https://cloud.githubusercontent.com/assets/22424216/19151791/4c4a2416-8c01-11e6-9af1-5ad5c4806775.PNG)

login as  any user (I login as ROBERTD)
Go to timecard, 
see attachment, the total hours show Total : 0.0

**Comment by mellissatort** [comment]
@eyuapptree this is a configuration issue where the sum attribute is lost at some point during the live-to-beta copy or promote beta-to-live process.  I have updated the configuration in lbredev.stanford.edu.  Please review and assign back to me if this is resolved.

**Comment by matthewtsmith** [comment]
@mellissatort Lets file a ticket for this for @sambbaron. I've seen this issue as well when testing Rice. The dataAttributeIndex for the sum attribute gets set to -1 in my testing. I believe this may be an issue with the builder reading in the accessory view info.
