### ISSUE TITLE
When exit a create form with default values on client, user is prompted to save/abandon changes

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#36]
App ID:  service.taylorfreezer.net (beta)

iOS 10.0.2
5.4.3 (2151)

Android 6.0.1-23
5.4.3 (1081)

Login:  rkromer

When user logs into client the Create Service Request create form displays.  Default values are configured for "Requester" and two hidden attributes Customer No and Store.  User navigates to menu and selects another menu item and is prompted with save/abandon message.  Since no changes were actually made and it was just default values displayed a user should not be prompted to save/abandon changes.

**Comment by matthewtsmith** [comment]
@mellissatort Fixed in 5.4.4 on both iOS and Android.

**Comment by mellissatort** [comment]
@matthewtsmith I am not seeing a 5.4.4 release in Crashlytics for iOS for this fix.  The latest I see is 5.5 (2190) on 10/4/2016.  I do see 5.4.4 in Crashlytics for Android.

**Comment by mellissatort** [comment]
@matthewtsmith I downloaded 5.5 (2207) from Crashlytics for iOS as that seemed more current.  Let me know if there is another version I should be testing with.

**Comment by mellissatort** [comment]
@matthewtsmith this issue was tested successfully with 5.4.4 (2214) but now with 5.4.4 (2215) it has reoccurred.
