### ISSUE TITLE
Add json setting valueFormat to data connector lists allowing enhanced configuration

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/revolution#4]
Currently we can configure an attribute with json setting valuFormat to display a descriptive label for an attribute value.  We do this on the page's attribute json setting configuration.

Example:

`{"valueFormat":{"format":"Serial#: $value","showIfEmpty":false}}`

Add this type of enhanced valueFormat configuration to data connector list display.  We would use this on a field such as Quantity on Hand which is an integer and add a descriptive format to it so it would display on the client like "Quantity on Hand: 10".

**Comment by matthewtsmith** [comment]
@sambbaron I think this is complete. It is on the client, not sure about the builder.

**Comment by sambbaron** [comment]
@matthewtsmith This is not implemented in the Portal yet.

**Comment by sambbaron** [comment]
@matthewtsmith Taking another look at this, and I don't understand where this is in the configuration.  Can you give me another example with full configuration context?

**Comment by sambbaron** [comment]
@matthewtsmith @mellissatort This has been deployed to sandbox `0.8.0-dev.3`.

Now in the List Display Editor you will see the gear button in the top-right of the template attributes, just like you would in a regular feature.  From there, you can edit the Value Format.

Matt, if we are going to make display of list attributes more similar to display of dataset attributes, then I would strongly ask that we make the JSON object the same as a regular DisplayElement within a feature group.  I am having to do a lot of workarounds in the Portal to use my DisplayElementModel, but output the JSON for the listDisplayOptionsv2 format.  My suggestion is to change `displayAttributes` to `displayElements`.
