### ISSUE TITLE
5.3.12 ANDROID: Error Determining Location

### ISSUE THREAD

**Issue by RobertGuinn** [apptreesoftware/revolution#61]
Galaxy S4
vendor.wawa.com
supertech

Tap Equipment Move
Tap Move To Arrow

"Determining Location"

and then

"Error, Unable To Determine Location"

Tap Pump Move

Tap Move To Arrow

gets: " No Results Found, There were no recored found within 1000 meters"

Two things:

It's not consistent.  I don't know what the correct behavior should be but it seem like I should get the No Result message in both cases.

**Comment by matthewtsmith** [comment]
@RobertGuinn Those are two different error messages for different reasons.
The first case it could not get your current location
The second case it got your location but there were no records within 1000 meters.
