### ISSUE TITLE
Remove menu icon when menu is visible

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/revolution#63]
<img width="505" alt="screen shot 2016-10-10 at 10 23 14 am" src="https://cloud.githubusercontent.com/assets/9000800/19244960/963ed6d2-8ed3-11e6-8e13-611bdcf01320.png">

**Comment by johnpryan** [comment]
fixed by https://github.com/apptreesoftware/apptreerevolution-web/commit/86381b78112fb4246d292808139bf4055f1a934f
