### ISSUE TITLE
Minus hours display "-" on both hour and minutes

### ISSUE THREAD

**Issue by eyuapptree** [apptreesoftware/revolution#69]
lbredev.stanford.edu
5.4.3 - 2173
login as ROBERTD
Go to  time card, find the entries on 9/20
The time entry on WO=1707897 is -0.5 hours
what it display is -0:-30, 
can we just display  -0:30 ?

![ed5678](https://cloud.githubusercontent.com/assets/22424216/19255635/962e804c-8f92-11e6-9f31-76e8fd8b462c.PNG)

**Comment by mellissatort** [comment]
@matthewtsmith this looks like a template configuration display issue on the client.  Can we include this fix in 5.5?

**Comment by matthewtsmith** [comment]
@mellissatort Fixed in 5.4.4
