### ISSUE TITLE
App crash when select employee on timecard

### ISSUE THREAD

**Issue by eyuapptree** [apptreesoftware/revolution#70]
lbreint.stanford.edu
5.4.3-2173 (ipad mini IOS 9.2 )
login as KJHCHANG
Go to  "Timecard", Tap on the employee lov under the calendar, select any employee --> app crash

**Comment by mellissatort** [comment]
@matthewtsmith I am not having this issue with app store download 5.4.3 (2151) but I am having this issue with 5.5 (2207).  From the timecard Choose Employee list I selected Jacob Herrera and the app crashed as soon as I did that.  This occurred at 5:18AM PT.  iOS version is 10.0.2.
