### ISSUE TITLE
Pusher notification not sent out when app is promoted to live

### ISSUE THREAD

**Issue by johnpryan** [apptreesoftware/revolution#71]
Steps to reproduce:
1. open Pusher debug console https://pusher.com/
2. save changes to a beta version
3. observe pusher message
4. promote app from beta to live
5. observe that no pusher message is emitted

**Comment by johnpryan** [comment]
@matthewtsmith The message should also distinguish the type of change (beta-to-live vs just a configuration-version update)

**Comment by alexisandreason** [comment]
@matthewtsmith @johnpryan Will we also want to trigger a pusher message when changing the beta version?

**Comment by matthewtsmith** [comment]
@alexisandreason yes
