### ISSUE TITLE
Cannot edit criteria for Display Element

### ISSUE THREAD

**Issue by johnpryan** [apptreesoftware/revolution#75]
**Description**

Unable to edit the criteria for the 'Zip' display element in the builder.

**Steps to Reproduce**

1. Open inspections app (Corrigo)
2. edit 'Zip' display element
3. Make a change to the criteria (delete or edit)
4. save
5. re-open 'Zip' display element
6. observe changes were not saved/applied

**App ID**
servicemaster.corrigo.com

**Version Number**
Beta Version 7

@sambbaron

**Comment by sambbaron** [comment]
@johnpryan I am working on this now.  Also, in the future, please copy in the portal URL for portal issues.  That eliminates the need to input much of the issue context: app ID, version, etc.

**Comment by sambbaron** [comment]
@johnpryan Fix deployed - build version `0.7.1`
