### ISSUE TITLE
Unable to create validation criteria in builder

### ISSUE THREAD

**Issue by johnpryan** [apptreesoftware/revolution#81]
**Description**

**Steps to Reproduce**

1. Open [the corrigo inspections app in the build](http://portal.apptreesoftware.com/#/app/servicemaster.corrigo.com/beta/builder/device/page/3576)
2. edit a display element
3. create validation criteria
4. observe that the validation criteria wasn't created

**App ID**
servicemaster.corrigo.com

**Version Number**
Beta Version 7
Portal Version 0.7.2

**Comment by johnpryan** [comment]
FYI @sambbaron

**Comment by sambbaron** [comment]
@johnpryan Fix deployed `0.7.6`
