### ISSUE TITLE
User exits app on device with Centralized Auth configured and on return get login failure

### ISSUE THREAD

**Issue by mellissatort** [apptreesoftware/revolution#87]
App IDs has Centralized authentication enabled and an external web url configured on the menu (ie. Campus Map).  When the user authenticates on the client and selects this external link they are redirected to a web browser like Safari.  If the user selects the "<Apptree" link at the top of the browser or closes the browser and reselects the AppTree app they then receive API Key Check Failed error or other login failure errors.  This does not occur if using a Cloud Native authentication (ie. somuat.stanford.edu). 

Steps to Reproduce:
Log into the application as centralized authenticated user
Click on Campus Map
Leaves app and goes to Safari->campus-map.stanford.edu
When select the AppTree link at the upper left and return to the AppTree application, it displays the error “API Key Check failed”.
You have to close the application completely, re-launch, repeat the login steps again.
Sometimes the login never works successfully and unable to access the application again.

Four separate issues were reported by the customer and screenshots are attached for each.
Issue #1. When I tried it, when I clicking on the home button back and forth, I did get the same API error. Attached screenshot. 
Issue #2, The app is prompting me for the authentication a lot. If I navigate out, and come back, it prompt me for the authentication again (within 5 minutes). 
Issue #3. I tried to relogin, after the authentication screen, it is giving me the Forbidden error. 
Issue #4. When I attempted to relogin, it is throwing the "Login Failed, unable to determine your username." 

App ID:  somuata.stanford.edu
SUNet Authentication Enabled.  Must work with Mellissa to login with mtort user account and Duo Auth

Version:
iOS 10.0.2    5.4.3 (2151) and 5.4.4 (2160)
Android 6.0.1   5.4.4 (1086)

![api key check failed error](https://cloud.githubusercontent.com/assets/22403044/19398407/6e2b50e0-921a-11e6-837f-01406ec41b5a.png)
![forbidden error](https://cloud.githubusercontent.com/assets/22403044/19398409/6e2e8594-921a-11e6-8d9c-00662b7c66ea.png)
![login failed error](https://cloud.githubusercontent.com/assets/22403044/19398408/6e2c6cd2-921a-11e6-9db2-a834d26f4d03.png)

**Comment by mellissatort** [comment]
@matthewtsmith Authentication error messages also appear when a user logs into the app successfully, clicks the device home button, selects the AppTree app icon and then the login failure displays.  The behavior on the device appears when you leave the app and then try to return back to the app.

**Comment by mellissatort** [comment]
@matthewtsmith This appears to be a unique issue to Stanford and their SUNet authentication configuration with the AppTree R5 app.  I tested Rice feandp.rice.edu app ID which is configured with their LDAP authentication and am not able to replicate the issue.  I am able to exit and return to the app without login failures or errors.

**Comment by matthewtsmith** [comment]
@RobertGuinn  @mellissatort Something must have changed on Stanford's end with SUNet. Our integration with them is now completely broken and the way that SUNet is redirecting is different. When did this break? Does it work with other apps? This could take 1-2 days to figure this out.

**Comment by matthewtsmith** [comment]
@RobertGuinn @mellissatort 
Here are the changes I've found compared to how we implemented it previously.

1.) Upon login, sometimes it doesn’t require you to do the DUO method if you have recently logged in. In that case it does not redirect you to the full URL. For example, it used to redirect to
`https://ofeam-mobile-uat.stanford.edu/hhsomm/`
but now it redirects to
`https://ofeam-mobile-uat.stanford.edu/`

But when you perform DUO it redirects you to the full URL like we expect

2.) Whenever the app opens we check the cookie by calling `https://ofeam-mobile-uat.stanford.edu/hhsomm/` and supplying the cookie. Previously, if the cookie was correct it would let us continue through to `https://ofeam-mobile-uat.stanford.edu/hhsomm/`

Now it loads a web page that you must then press “Continue” on.


The problem with that is that is also what happens if your cookie is bad, it redirects you to a login page.
So I have no way to know what the purpose of the page is

**Comment by mellissatort** [comment]
@matthewtsmith Stanford made two updates to resolve this issue.

1) On the load balancer side, set default persistence profile for virtual server 
ofeam-mobile-uat on bigipdev which was not set earlier
2) Re-enable webauth in UAT.  Stanford had updated server for Shibboleth instead of webauth and did not notify AppTree of this change.

Since the issue is resolved with these two updates by Stanford I am going to close this ticket.
