### ISSUE TITLE
New editable "ListToggle" template for repeating elements

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/revolution#88]
We need a another template for Corrigo that allows us to use ListToggle on a repeating element.

The layout will look like this:

<img width="526" alt="screen shot 2016-10-14 at 4 35 46 pm" src="https://cloud.githubusercontent.com/assets/9000800/19405445/50dcc084-922c-11e6-9bf6-03e8318a9be9.png">

This will be Template ID `3`

**Comment by matthewtsmith** [comment]
@sambbaron Marking as critical. Need this monday AM for dev on Corrigo.

**Comment by sambbaron** [comment]
@matthewtsmith This is deployed to portal `0.7.5`
