### ISSUE TITLE
550 response on PUT portal/authParameters

### ISSUE THREAD

**Issue by sambbaron** [apptreesoftware/revolution#90]
Please see the attached cURL.  I am getting a 550 response on `PUT /portal/authParameters` with the user registration changes.  The response is `{message: null}`.

[curl.txt](https://github.com/apptreesoftware/revolution/files/534281/curl.txt)

**Comment by alexisandreason** [comment]
This was a discrepancy between the config that the core and portal expected. I updated the app authentication object to send the entire dataset rather than just the service config

**Comment by sambbaron** [comment]
@alexisandreason Still getting a 550 response

[curl.txt](https://github.com/apptreesoftware/revolution/files/534945/curl.txt)

**Comment by alexisandreason** [comment]
@sambbaron The 550 was because defaultRoleIDs was null. I added a null check and was able to save the auth config from the given curl.

**Comment by sambbaron** [comment]
@alexisandreason I'll also fix this on my end
