### ISSUE TITLE
Core not saving/setting create and update flags on custom user attributes

### ISSUE THREAD

**Issue by sambbaron** [apptreesoftware/revolution#93]
I am assuming that all custom user attributes should have the `create` and `update` flags set to true so they can be used on create and update forms.

I think the Core should set these flags.  Regardless, even if I try to set them through the Portal, they are not being saved.

[curl.txt](https://github.com/apptreesoftware/revolution/files/536870/curl.txt)

**Comment by alexisandreason** [comment]
This has been resolved. Please test and close issue.
