### ISSUE TITLE
List Display Defaults

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/revolution#94]
1. Default list template should be "Single Attribute" with attribute0 as the default value.
2. List Display Options for newly added SelectList Display Elements should have `Default` selected instead of `Custom`

I find myself having to make these changes almost every time so we should just make it default.

**Comment by sambbaron** [comment]
@matthewtsmith This has been deployed to sandbox `0.8.0-dev.20` and will be in my next services1 deploy.  I was unable to replicate issue 2.
